import { useLocation } from "react-router-dom";

function ResultPage() {
  const location = useLocation();
  const image = location.state?.image;

  return (
    <div className="min-h-screen bg-gray-50 flex justify-center p-4 text-center">
      <div className="w-full max-w-md bg-white rounded-xl p-4">

        {/* Header */}
        <h1 className="text-lg font-semibold mb-4">
          Analysis Results
        </h1>

        {/* Image */}
        <div className="relative mb-4">
          <img
            src={image}
            alt="Skin"
            className="w-full h-56 object-cover rounded-xl mx-auto"
          />
          <span className="absolute top-3 right-3 bg-white px-3 py-1 rounded-full text-sm font-medium text-green-600 shadow">
            ✅ ANALYZED
          </span>
        </div>

        {/* Result */}
        <div className="bg-white rounded-xl p-4 shadow mb-4 border border-gray-200">
          <h2 className="text-xl font-bold mb-1">Eczema</h2>

          <p className="text-gray-500 text-sm mb-2">
            (Atopic Dermatitis)
          </p>

          <span className="inline-block bg-orange-100 text-orange-600 px-4 py-1 rounded-full text-sm font-medium mb-3">
            ⚠ Requires Care
          </span>

          {/* Confidence */}
          <div className="mb-4">
            <div className="flex justify-between text-sm font-medium mb-1">
              <span>Match Confidence</span>
              <span className="text-teal-500">94%</span>
            </div>

            <div className="w-full bg-gray-200 rounded-full h-2">
              <div className="bg-teal-400 h-2 rounded-full w-[94%]" />
            </div>
          </div>

          <p className="text-gray-600 text-sm leading-relaxed">
            Atopic dermatitis is a common condition that makes your skin red and itchy.
            It is chronic and may flare periodically. It may be associated with asthma
            or hay fever.
          </p>
        </div>

        {/* Precautions */}
        <h3 className="text-lg font-semibold mb-3">
          Suggested Precautions
        </h3>

        <div className="space-y-3 mb-4">
          <Precaution
            icon="💧"
            title="Moisturize Daily"
            desc="Apply cream twice a day"
          />
          <Precaution
            icon="🧼"
            title="Avoid Irritants"
            desc="Use gentle, unscented soaps"
          />
          <Precaution
            icon="✋"
            title="Don't Scratch"
            desc="Keep nails short to avoid injury"
          />
        </div>

        {/* Disclaimer */}
        <div className="bg-teal-50 border border-teal-200 rounded-xl p-4 text-sm text-teal-700">
          <strong>AI Analysis Disclaimer</strong>
          <p className="mt-1">
            This result is generated by artificial intelligence and is not a medical
            diagnosis. Please consult a certified dermatologist.
          </p>
        </div>
      </div>
    </div>
  );
}

function Precaution({ icon, title, desc }) {
  return (
    <div className="flex items-start gap-3 bg-gray-50 p-4 rounded-xl">
      <div className="text-2xl">{icon}</div>
      <div className="text-left">
        <h4 className="font-semibold text-sm">{title}</h4>
        <p className="text-xs text-gray-500">{desc}</p>
      </div>
    </div>
  );
}

export default ResultPage;
